# Generated by Django 3.2.7 on 2021-12-07 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import marketplace.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.category')),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tutor', serialize=False, to='login.user')),
                ('summary', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=marketplace.models._get_image_path)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.FloatField(null=True)),
                ('num_rating', models.IntegerField(null=True)),
                ('stripe_account_id', models.CharField(max_length=30, null=True)),
                ('linkedin_url', models.URLField(null=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('specialties', models.ManyToManyField(blank=True, to='marketplace.Category')),
            ],
            options={
                'ordering': ('-rating', '-num_rating', 'price'),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('min_price', models.IntegerField(db_index=True)),
                ('max_price', models.IntegerField(db_index=True)),
                ('level', models.CharField(db_index=True, default=None, max_length=30, null=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default='Other', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='post_category', to='marketplace.category')),
                ('type', models.ForeignKey(default='Other', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='type', to='marketplace.category')),
            ],
            options={
                'ordering': ('-time_created',),
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('room_url', models.URLField(null=True)),
                ('duration', models.IntegerField(default=55)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('tutee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='marketplace.tutorprofile')),
            ],
            options={
                'ordering': ('date_time',),
            },
        ),
    ]
