# Generated by Django 3.2.7 on 2022-01-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20220111_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='num_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
