# Generated by Django 3.2.7 on 2022-01-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20220111_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
