# Generated by Django 3.2.7 on 2022-01-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_appointment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='number_used',
            field=models.IntegerField(default=1),
        ),
    ]
