# Generated by Django 3.2.7 on 2022-01-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_category_number_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='account_activated',
            field=models.BooleanField(default=False),
        ),
    ]
