# Generated by Django 3.2.7 on 2022-01-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_tutorprofile_account_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
