# Generated by Django 3.2.7 on 2022-01-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_tutorprofile_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method_id',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
