# Generated by Django 3.2.7 on 2022-01-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_appointment_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='available', max_length=30),
        ),
    ]
