# Generated by Django 3.2.7 on 2022-01-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_intent_id',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
