# Generated by Django 3.2.7 on 2022-02-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_auto_20220131_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cost',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
