# Generated by Django 3.2.7 on 2022-02-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_appointment_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='unconfirmed_count',
            field=models.IntegerField(default=0),
        ),
    ]
