# Generated by Django 3.2.7 on 2022-02-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_tutorprofile_unconfirmed_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
