# Generated by Django 3.2.7 on 2022-02-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_auto_20220204_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cost',
            field=models.IntegerField(default=100),
        ),
    ]
