# Generated by Django 3.2.7 on 2022-02-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_alter_appointment_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='unconfirmed_count',
        ),
    ]
