# Generated by Django 3.2.7 on 2022-02-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_remove_tutorprofile_unconfirmed_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('pending', 'pending'), ('confirmed', 'confirmed')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
