# Generated by Django 3.2.7 on 2022-01-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
