# Generated by Django 3.2.7 on 2022-03-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecell',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
